# Generated by Django 5.1.15 on 2026-08-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditledger",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PARTIAL", "Partial"),
                    ("PAID", "Paid"),
                    ("OVERDUE", "Overdue"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
