# Generated by Django 5.1.15 on 2026-08-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="tags",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
