# Generated by Django 5.1.15 on 2026-07-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="whatsapp_number",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
